### ISSUE TITLE
How to build app?

### ISSUE THREAD

**Issue by seldamat** [opscientia/society-home#2]
What are the step by step instructions to build and run the application? The current documentation just builds an example application. Steps should be added to the documentation for others to follow.

**Comment by seldamat** [comment]
steps that worked for me

> git clone https://github.com/opscientia/verse build
> npx create-next-app --example https://github.com/opscientia/verse build
> cd build
> npm run build
> npm run start

**Comment by seldamat** [comment]
@Rashmi-278 can we update the vercel link to opsci-society from opsci-verse since these are different applications?

**Comment by Rashmi-278** [comment]
Yes, Done

Sorry about that, missed updating it before
