### ISSUE TITLE
Server Error 500

### ISSUE THREAD

**Issue by seldamat** [opscientia/society-home#3]
There appears to be an issue following the most recent push with passport integration for user sessions that results in a server error 500. There also are issues with the application on mobile that result to random crashes. 

On my machine:
https://opscientia.com works
https://opsci.io doesn't

On my mobile device
- neither link works

Other folks report neither link works

Could be a combination of DNS settings + deployment bugs relating to most recent updates adding user sessions and sign in with ORCID.

**Comment by Rashmi-278** [comment]
This issue was caused due to redirection in the index page and react states in cookie.tsx 

Removing redirection and adding ? before using dot notation solved it
by adding ? we check if the parameter exists or not before using it or performing action on it , so it doesn't crash
